// #region Global Imports
import Head from "next/head"
import styled from "styled-components"
// #endregion Global Imports

// #region Local Imports
import { Header, Button, Title, SizeCode } from "@Components"
import { ILayout } from "../Layout"
import { StyledWrap } from "./styled"

// #endregion Local Imports

export const Default = function ({ children }: ILayout.IProps) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css"></link>
            </Head>
            <StyledWrap className="l_wrap">
                <Header>
                    <Title>로고</Title>
                    <Button href={"/setting"}>
                        <i className="xi-cog"></i>
                        <span className="ir">설정</span>
                    </Button>
                </Header>
                {children}
            </StyledWrap>
        </>
    )
}
