import { CATE, Subcate } from "@Interfaces"

export const SUBCATE_LIST: Subcate[] = [
    {
        seq: 1,
        name: "pork",
        icon: "/static/images/items/icon_pork.svg",
        cate: CATE.MEAT,
        seqList: [285, 52, 99],
    },
    {
        seq: 2,
        name: "beef",
        icon: "/static/images/items/icon_beef.svg",
        cate: CATE.MEAT,
        seqList: [278, 58, 82, 131, 106],
    },
    {
        seq: 3,
        name: "chicken",
        icon: "/static/images/items/icon_chicken.svg",
        cate: CATE.MEAT,
        seqList: [18, 275, 283, 138],
    },
    {
        seq: 4,
        name: "egg",
        icon: "/static/images/items/icon_egg.svg",
        cate: CATE.MEAT,
        seqList: [171, 321, 320, 181],
    },
    {
        seq: 5,
        name: "mackerel",
        cate: CATE.FISH,
        seqList: [13, 266, 267, 268, 269, 316, 318],
    },
    {
        seq: 6,
        name: "croaker",
        cate: CATE.FISH,
        seqList: [303, 258, 259, 261, 260, 135, 313, 314],
    },
    {
        seq: 7,
        name: "pollock",
        cate: CATE.FISH,
        seqList: [302, 262, 263, 264, 265, 184, 152, 315],
    },
    {
        seq: 8,
        name: "dongtae",
        cate: CATE.FISH,
        seqList: [288],
    },
    {
        seq: 9,
        name: "squid",
        cate: CATE.FISH,
        seqList: [253, 54, 254, 256, 255, 257],
    },
    {
        seq: 10,
        name: "napa-cabbage",
        cate: CATE.VEGETABLE,
        seqList: [26, 125, 271, 307],
    },
    {
        seq: 11,
        name: "lettuce",
        cate: CATE.VEGETABLE,
        seqList: [23, 310],
    },
    {
        seq: 12,
        name: "radish",
        cate: CATE.VEGETABLE,
        seqList: [25, 133, 274, 308],
    },
    {
        seq: 13,
        name: "onion",
        cate: CATE.VEGETABLE,
        seqList: [24, 309],
    },
    {
        seq: 14,
        name: "cucumber",
        cate: CATE.VEGETABLE,
        seqList: [22, 311],
    },
    {
        seq: 15,
        name: "korean-pear",
        cate: CATE.VEGETABLE,
        seqList: [27, 284, 276, 248, 306],
    },
    {
        seq: 16,
        name: "apple",
        cate: CATE.VEGETABLE,
        seqList: [28, 50, 305, 270, 244, 279],
    },
    {
        seq: 17,
        name: "kabocha",
        cate: CATE.VEGETABLE,
        seqList: [277, 119, 118],
    },
    {
        seq: 18,
        name: "zucchini",
        cate: CATE.VEGETABLE,
        seqList: [312],
    },
]
export const ITEM_OBJ = {
    285: { A_NAME: "pork", A_NAME_DATA: "돼지고기", A_UNIT: ["600g", "1근"] },
    52: { A_NAME: "pork(pork-belly)", A_NAME_DATA: "돼지고기(삼겹살)", A_UNIT: ["600g", "1근"] },
    99: { A_NAME: "pork(raw-pork-belly)", A_NAME_DATA: "돼지고기(생삼겹살)", A_UNIT: ["600g", "1근"] },
    278: { A_NAME: "beef", A_NAME_DATA: "쇠고기", A_UNIT: ["600g", "1근"] },
    58: { A_NAME: "beef(korean-beef,bulgogi)", A_NAME_DATA: "쇠고기(한우,불고기)", A_UNIT: ["600g", "1근"] },
    82: { A_NAME: "beef(non-korean-beef,bulgogi)", A_NAME_DATA: "쇠고기(육우,불고기)", A_UNIT: ["600g", "1근"] },
    131: { A_NAME: "beef(korean-beef-grade-1)", A_NAME_DATA: "쇠고기(한우1등급)", A_UNIT: ["600g", "1근"] },
    106: { A_NAME: "beef(korean-beef-grade-2)", A_NAME_DATA: "쇠고기(한우2등급)", A_UNIT: ["600g", "1근"] },
    18: { A_NAME: "chicken", A_NAME_DATA: "닭고기", A_UNIT: ["1마리"] },
    275: { A_NAME: "chicken(middle)", A_NAME_DATA: "닭고기(중간)", A_UNIT: ["1마리", "1kg"] },
    283: { A_NAME: "chicken(broiler)", A_NAME_DATA: "닭고기(육계)", A_UNIT: ["1마리", "1kg"] },
    138: { A_NAME: "chicken(native)", A_NAME_DATA: "닭고기(토종닭)", A_UNIT: ["1마리"] },
    171: { A_NAME: "egg(10-eggs)", A_NAME_DATA: "달걀(10개)", A_UNIT: ["10개"] },
    321: { A_NAME: "egg(15-eggs)", A_NAME_DATA: "달걀(15개)", A_UNIT: ["15개", "특란"] },
    320: { A_NAME: "egg(30-eggs)", A_NAME_DATA: "달걀(30개)", A_UNIT: ["30개", "특란"] },
    181: { A_NAME: "egg(68g+)", A_NAME_DATA: "달걀(왕란)", A_UNIT: ["30개"] },
    13: { A_NAME: "mackerel", A_NAME_DATA: "고등어", A_UNIT: ["1마리"] },
    266: { A_NAME: "mackerel(raw,korea)", A_NAME_DATA: "고등어(생물,국산)", A_UNIT: ["1마리"] },
    267: { A_NAME: "mackerel(raw,imported)", A_NAME_DATA: "고등어(생물,수입산)", A_UNIT: ["1마리"] },
    268: { A_NAME: "mackerel(frozen,korea)", A_NAME_DATA: "고등어(냉동,국산)", A_UNIT: ["1마리"] },
    269: { A_NAME: "mackerel(frozen,imported)", A_NAME_DATA: "고등어(냉동,수입산)", A_UNIT: ["1마리"] },
    316: { A_NAME: "mackerel(30cm,korea)", A_NAME_DATA: "고등어(30cm,국산)", A_UNIT: ["1마리"] },
    318: { A_NAME: "mackerel(30cm,imported)", A_NAME_DATA: "고등어(30cm,수입산)", A_UNIT: ["1마리"] },
    303: { A_NAME: "croaker", A_NAME_DATA: "조기", A_UNIT: ["1마리"] },
    258: { A_NAME: "croaker(raw,korea)", A_NAME_DATA: "조기(생물,국산)", A_UNIT: ["1마리"] },
    259: { A_NAME: "croaker(raw,imported)", A_NAME_DATA: "조기(냉동,국산)", A_UNIT: ["1마리"] },
    261: { A_NAME: "croaker(raw,china)", A_NAME_DATA: "조기(생물,수입산)", A_UNIT: ["1마리"] },
    260: { A_NAME: "croaker(frozen,korea)", A_NAME_DATA: "조기(냉동,수입산)", A_UNIT: ["1마리"] },
    135: { A_NAME: "croaker(frozen,imported)", A_NAME_DATA: "조기(중국산,생물)", A_UNIT: ["1마리"] },
    314: { A_NAME: "frozen-yellow-croaker(20cm,korea)", A_NAME_DATA: "냉동참조기(20cm,국산)", A_UNIT: ["1마리"] },
    313: { A_NAME: "frozen-yellow-croaker(20cm,imported)", A_NAME_DATA: "냉동참조기(20cm,수입)", A_UNIT: ["1마리"] },
    302: { A_NAME: "pollock", A_NAME_DATA: "명태", A_UNIT: ["1마리"] },
    262: { A_NAME: "pollock(raw,korea)", A_NAME_DATA: "명태(생물,국산)", A_UNIT: ["1마리"] },
    263: { A_NAME: "pollock(raw,imported)", A_NAME_DATA: "명태(냉동,국산)", A_UNIT: ["1마리"] },
    264: { A_NAME: "pollock(frozen,korea)", A_NAME_DATA: "명태(냉동,수입산)", A_UNIT: ["1마리"] },
    265: { A_NAME: "pollock(frozen,imported)", A_NAME_DATA: "명태(생물,수입산)", A_UNIT: ["1마리"] },
    184: { A_NAME: "pollock(frozen,japan)", A_NAME_DATA: "명태(일본산,냉동)", A_UNIT: ["500g"] },
    152: { A_NAME: "pollock(frozen,russia)", A_NAME_DATA: "명태(러시아,냉동)", A_UNIT: ["1마리"] },
    315: { A_NAME: "pollock(45cm,imported)", A_NAME_DATA: "명태(45cm,수입산)", A_UNIT: ["1마리"] },
    288: { A_NAME: "dongtae", A_NAME_DATA: "동태", A_UNIT: ["1마리"] },
    253: { A_NAME: "squid", A_NAME_DATA: "오징어", A_UNIT: ["1마리"] },
    54: { A_NAME: "squid(frozen)", A_NAME_DATA: "오징어(냉동)", A_UNIT: ["1마리"] },
    254: { A_NAME: "squid(raw,korea)", A_NAME_DATA: "오징어(생물,국산)", A_UNIT: ["1마리"] },
    256: { A_NAME: "squid(raw,imported)", A_NAME_DATA: "오징어(냉동,국산)", A_UNIT: ["1마리"] },
    255: { A_NAME: "squid(frozen,korea)", A_NAME_DATA: "오징어(생물,수입산)", A_UNIT: ["1마리"] },
    257: { A_NAME: "squid(frozen,imported)", A_NAME_DATA: "오징어(냉동,수입산)", A_UNIT: ["1마리"] },
    26: { A_NAME: "napa-cabbage", A_NAME_DATA: "배추", A_UNIT: ["1포기"] },
    125: { A_NAME: "napa-cabbage(korea)", A_NAME_DATA: "배추(국산)", A_UNIT: ["1포기"] },
    271: { A_NAME: "napa-cabbage(middle)", A_NAME_DATA: "배추(중간)", A_UNIT: ["1포기"] },
    307: { A_NAME: "napa-cabbage(2.5~3kg)", A_NAME_DATA: "배추(2.5~3kg)", A_UNIT: ["1포기", "1개"] },
    23: { A_NAME: "lettuce", A_NAME_DATA: "상추", A_UNIT: ["100g"] },
    310: { A_NAME: "lettuce(100g)", A_NAME_DATA: "상추(100g)", A_UNIT: ["100g", "1봉지"] },
    25: { A_NAME: "radish", A_NAME_DATA: "무", A_UNIT: ["1개"] },
    133: { A_NAME: "radish(washed)", A_NAME_DATA: "무(세척무)", A_UNIT: ["1개"] },
    274: { A_NAME: "radish(washed,middle)", A_NAME_DATA: "무(세척무, 중)", A_UNIT: ["1개"] },
    308: { A_NAME: "radish(1kg)", A_NAME_DATA: "무(1kg)", A_UNIT: ["1개", "1kg"] },
    24: { A_NAME: "onion", A_NAME_DATA: "양파", A_UNIT: ["1.5kg"] },
    309: { A_NAME: "onion(1.5kg)", A_NAME_DATA: "양파(1.5kg망)", A_UNIT: ["1망", "1.5kg"] },
    22: { A_NAME: "cucumber", A_NAME_DATA: "오이", A_UNIT: ["1개"] },
    311: { A_NAME: "cucumber(tadagi-cucumber)", A_NAME_DATA: "오이(다다기)", A_UNIT: ["1개", "1 개"] },
    27: { A_NAME: "korean-pear", A_NAME_DATA: "배", A_UNIT: ["1개"] },
    284: { A_NAME: "korean-pear(intermediate-quality)", A_NAME_DATA: "배(중품)", A_UNIT: ["1개"] },
    276: { A_NAME: "korean-pear(新高)", A_NAME_DATA: "배(신고)", A_UNIT: ["1개"] },
    248: { A_NAME: "korean-pear(新高),big", A_NAME_DATA: "배(신고),중급(대)", A_UNIT: ["1개", "1 개"] },
    306: { A_NAME: "korean-pear(新高,600g)", A_NAME_DATA: "배(신고, 600g)", A_UNIT: ["1개", "600g"] },
    28: { A_NAME: "apple", A_NAME_DATA: "사과", A_UNIT: ["1개"] },
    50: { A_NAME: "apple(富士)", A_NAME_DATA: "사과(부사)", A_UNIT: ["1개"] },
    305: { A_NAME: "apple(富士,300g)", A_NAME_DATA: "사과(부사, 300g)", A_UNIT: ["1개", "300g"] },
    270: { A_NAME: "apple(富士),middle", A_NAME_DATA: "사과(부사),중급(중)", A_UNIT: ["1개"] },
    244: { A_NAME: "apple(富士),big", A_NAME_DATA: "사과(부사),중급(대)", A_UNIT: ["1개", "1 개"] },
    279: { A_NAME: "apple(intermediate-quality)", A_NAME_DATA: "사과(중품)", A_UNIT: ["1개"] },
    277: { A_NAME: "kabocha", A_NAME_DATA: "호박", A_UNIT: ["1개"] },
    119: { A_NAME: "kabocha(incubator)", A_NAME_DATA: "호박(인큐베이터)", A_UNIT: ["1개"] },
    118: { A_NAME: "kabocha(incubator),intermediate-quality", A_NAME_DATA: "호박(인큐베이터),중간", A_UNIT: ["1개"] },
    312: { A_NAME: "zucchini", A_NAME_DATA: "애호박", A_UNIT: ["1개", "1 개"] },
} as const
export const M_TYPE: {
    [x: string]: string
} = {
    "": "",
    "001": "traditional-market",
    "002": "supermarket",
} as const
export type M_TYPE = typeof M_TYPE[keyof typeof M_TYPE]
export const M_TYPE_DATA: {
    [x: string]: string
} = {
    "": "",
    "001": "전통시장",
    "002": "대형마트",
} as const
export const M_GU: {
    [x: string]: string
} = {
    "": "",
    "680000": "강남구",
    "440000": "마포구",
    "305000": "강북구",
    "650000": "서초구",
    "710000": "송파구",
    "380000": "은평구",
    "290000": "성북구",
    "590000": "동작구",
    "350000": "노원구",
    "470000": "양천구",
    "170000": "용산구",
    "320000": "도봉구",
    "740000": "강동구",
    "410000": "서대문구",
    "215000": "광진구",
    "545000": "금천구",
    "620000": "관악구",
    "110000": "종로구",
    "140000": "중구",
    "200000": "성동구",
    "500000": "강서구",
    "530000": "구로구",
    "560000": "영등포구",
    "260000": "중랑구",
    "230000": "동대문구",
} as const
export const M_TYPE_CODE_LIST = Object.keys(M_TYPE_DATA)
export const M_GU_CODE_LIST = Object.keys(M_GU)
