import { Category, PriceGroup } from "@Interfaces"

export const CATEGORY_TYPE = {
    STAR: 0,
    MEAT: 1,
    FISH: 2,
    VEGETABLE: 3,
} as const
export type CATEGORY_TYPE = typeof CATEGORY_TYPE[keyof typeof CATEGORY_TYPE]

export const CATEGORY_TYPE_STR: { [x: number]: string } = {
    [CATEGORY_TYPE.STAR]: "favorites",
    [CATEGORY_TYPE.MEAT]: "meat",
    [CATEGORY_TYPE.FISH]: "fish",
    [CATEGORY_TYPE.VEGETABLE]: "vegetable",
} as const
export type CATEGORY_TYPE_STR = typeof CATEGORY_TYPE_STR[keyof typeof CATEGORY_TYPE_STR]

export const M_TYPE: {
    [x: string]: string
} = {
    "": "",
    "001": "traditional-market",
    "002": "supermarket",
} as const
export type M_TYPE = typeof M_TYPE[keyof typeof M_TYPE]

export const M_GU: {
    [x: string]: string
} = {
    "": "",
    "680000": "강남구",
    "440000": "마포구",
    "305000": "강북구",
    "650000": "서초구",
    "710000": "송파구",
    "380000": "은평구",
    "290000": "성북구",
    "590000": "동작구",
    "350000": "노원구",
    "470000": "양천구",
    "170000": "용산구",
    "320000": "도봉구",
    "740000": "강동구",
    "410000": "서대문구",
    "215000": "광진구",
    "545000": "금천구",
    "620000": "관악구",
    "110000": "종로구",
    "140000": "중구",
    "200000": "성동구",
    "500000": "강서구",
    "530000": "구로구",
    "560000": "영등포구",
    "260000": "중랑구",
    "230000": "동대문구",
} as const
export type M_GU = typeof M_GU[keyof typeof M_GU]

export const CATEGORY_LIST: Category[] = [
    {
        seq: 1,
        name: "pork",
        icon: "/static/images/items/icon_pork.svg",
        type: CATEGORY_TYPE.MEAT,
        seq_list: [285, 52, 99],
    },
    {
        seq: 2,
        name: "beef",
        icon: "/static/images/items/icon_beef.svg",
        type: CATEGORY_TYPE.MEAT,
        seq_list: [278, 58, 82, 131, 106],
    },
    {
        seq: 3,
        name: "chicken",
        icon: "/static/images/items/icon_chicken.svg",
        type: CATEGORY_TYPE.MEAT,
        seq_list: [18, 275, 283, 138],
    },
    {
        seq: 4,
        name: "egg",
        icon: "/static/images/items/icon_egg.svg",
        type: CATEGORY_TYPE.MEAT,
        seq_list: [171, 321, 320, 181],
    },
    {
        seq: 5,
        name: "mackerel",
        type: CATEGORY_TYPE.FISH,
        seq_list: [13, 266, 267, 268, 269, 316, 318],
    },
    {
        seq: 6,
        name: "croaker",
        type: CATEGORY_TYPE.FISH,
        seq_list: [303, 258, 259, 261, 260, 135, 313, 314],
    },
    {
        seq: 7,
        name: "pollock",
        type: CATEGORY_TYPE.FISH,
        seq_list: [302, 262, 263, 264, 265, 184, 152, 315],
    },
    {
        seq: 8,
        name: "dongtae",
        type: CATEGORY_TYPE.FISH,
        seq_list: [288],
    },
    {
        seq: 9,
        name: "squid",
        type: CATEGORY_TYPE.FISH,
        seq_list: [253, 54, 254, 256, 255, 257],
    },
    {
        seq: 10,
        name: "napa-cabbage",
        type: CATEGORY_TYPE.VEGETABLE,
        seq_list: [26, 125, 271, 307],
    },
    {
        seq: 11,
        name: "lettuce",
        type: CATEGORY_TYPE.VEGETABLE,
        seq_list: [23, 310],
    },
    {
        seq: 12,
        name: "radish",
        type: CATEGORY_TYPE.VEGETABLE,
        seq_list: [25, 133, 274, 308],
    },
    {
        seq: 13,
        name: "onion",
        type: CATEGORY_TYPE.VEGETABLE,
        seq_list: [24, 309],
    },
    {
        seq: 14,
        name: "cucumber",
        type: CATEGORY_TYPE.VEGETABLE,
        seq_list: [22, 311],
    },
    {
        seq: 15,
        name: "korean-pear",
        type: CATEGORY_TYPE.VEGETABLE,
        seq_list: [27, 284, 276, 248, 306],
    },
    {
        seq: 16,
        name: "apple",
        type: CATEGORY_TYPE.VEGETABLE,
        seq_list: [28, 50, 305, 270, 244, 279],
    },
    {
        seq: 17,
        name: "kabocha",
        type: CATEGORY_TYPE.VEGETABLE,
        seq_list: [277, 119, 118],
    },
    {
        seq: 18,
        name: "zucchini",
        type: CATEGORY_TYPE.VEGETABLE,
        seq_list: [312],
    },
]
export const NAME_OBJ: { [x: number]: PriceGroup } = {
    285: { A_NAME: "pork", A_UNIT: ["600g", "1근"] },
    52: { A_NAME: "pork(pork-belly)", A_UNIT: ["600g", "1근"] },
    99: { A_NAME: "pork(raw-pork-belly)", A_UNIT: ["600g", "1근"] },
    278: { A_NAME: "beef", A_UNIT: ["600g", "1근"] },
    58: { A_NAME: "beef(korean-beef,bulgogi)", A_UNIT: ["600g", "1근"] },
    82: { A_NAME: "beef(non-korean-beef,bulgogi)", A_UNIT: ["600g", "1근"] },
    131: { A_NAME: "beef(korean-beef-grade-1)", A_UNIT: ["600g", "1근"] },
    106: { A_NAME: "beef(korean-beef-grade-2)", A_UNIT: ["600g", "1근"] },
    18: { A_NAME: "chicken", A_UNIT: ["1마리"] },
    275: { A_NAME: "chicken(middle)", A_UNIT: ["1마리", "1kg"] },
    283: { A_NAME: "chicken(broiler)", A_UNIT: ["1마리", "1kg"] },
    138: { A_NAME: "chicken(native)", A_UNIT: ["1마리"] },
    171: { A_NAME: "egg(10-eggs)", A_UNIT: ["10개"] },
    321: { A_NAME: "egg(15-eggs)", A_UNIT: ["15개", "특란"] },
    320: { A_NAME: "egg(30-eggs)", A_UNIT: ["30개", "특란"] },
    181: { A_NAME: "egg(68g+)", A_UNIT: ["30개"] },
    13: { A_NAME: "mackerel", A_UNIT: ["1마리"] },
    266: { A_NAME: "mackerel(raw,korea)", A_UNIT: ["1마리"] },
    267: { A_NAME: "mackerel(raw,imported)", A_UNIT: ["1마리"] },
    268: { A_NAME: "mackerel(frozen,korea)", A_UNIT: ["1마리"] },
    269: { A_NAME: "mackerel(frozen,imported)", A_UNIT: ["1마리"] },
    316: { A_NAME: "mackerel(30cm,korea)", A_UNIT: ["1마리"] },
    318: { A_NAME: "mackerel(30cm,imported)", A_UNIT: ["1마리"] },
    303: { A_NAME: "croaker", A_UNIT: ["1마리"] },
    258: { A_NAME: "croaker(raw,korea)", A_UNIT: ["1마리"] },
    261: { A_NAME: "croaker(raw,imported)", A_UNIT: ["1마리"] },
    135: { A_NAME: "croaker(raw,china)", A_UNIT: ["1마리"] },
    259: { A_NAME: "croaker(frozen,korea)", A_UNIT: ["1마리"] },
    260: { A_NAME: "croaker(frozen,imported)", A_UNIT: ["1마리"] },
    314: { A_NAME: "frozen-yellow-croaker(20cm,korea)", A_UNIT: ["1마리"] },
    313: { A_NAME: "frozen-yellow-croaker(20cm,imported)", A_UNIT: ["1마리"] },
    302: { A_NAME: "pollock", A_UNIT: ["1마리"] },
    262: { A_NAME: "pollock(raw,korea)", A_UNIT: ["1마리"] },
    265: { A_NAME: "pollock(raw,imported)", A_UNIT: ["1마리"] },
    263: { A_NAME: "pollock(frozen,korea)", A_UNIT: ["1마리"] },
    264: { A_NAME: "pollock(frozen,imported)", A_UNIT: ["1마리"] },
    184: { A_NAME: "pollock(frozen,japan)", A_UNIT: ["500g"] },
    152: { A_NAME: "pollock(frozen,russia)", A_UNIT: ["1마리"] },
    315: { A_NAME: "pollock(45cm,imported)", A_UNIT: ["1마리"] },
    288: { A_NAME: "dongtae", A_UNIT: ["1마리"] },
    253: { A_NAME: "squid", A_UNIT: ["1마리"] },
    54: { A_NAME: "squid(frozen)", A_UNIT: ["1마리"] },
    254: { A_NAME: "squid(raw,korea)", A_UNIT: ["1마리"] },
    255: { A_NAME: "squid(raw,imported)", A_UNIT: ["1마리"] },
    256: { A_NAME: "squid(frozen,korea)", A_UNIT: ["1마리"] },
    257: { A_NAME: "squid(frozen,imported)", A_UNIT: ["1마리"] },
    26: { A_NAME: "napa-cabbage", A_UNIT: ["1포기"] },
    125: { A_NAME: "napa-cabbage(korea)", A_UNIT: ["1포기"] },
    271: { A_NAME: "napa-cabbage(middle)", A_UNIT: ["1포기"] },
    307: { A_NAME: "napa-cabbage(2.5~3kg)", A_UNIT: ["1포기", "1개"] },
    23: { A_NAME: "lettuce", A_UNIT: ["100g"] },
    310: { A_NAME: "lettuce(100g)", A_UNIT: ["100g", "1봉지"] },
    25: { A_NAME: "radish", A_UNIT: ["1개"] },
    133: { A_NAME: "radish(washed)", A_UNIT: ["1개"] },
    274: { A_NAME: "radish(washed,middle)", A_UNIT: ["1개"] },
    308: { A_NAME: "radish(1kg)", A_UNIT: ["1개", "1kg"] },
    24: { A_NAME: "onion", A_UNIT: ["1.5kg"] },
    309: { A_NAME: "onion(1.5kg)", A_UNIT: ["1망", "1.5kg"] },
    22: { A_NAME: "cucumber", A_UNIT: ["1개"] },
    311: { A_NAME: "cucumber(tadagi-cucumber)", A_UNIT: ["1개", "1 개"] },
    27: { A_NAME: "korean-pear", A_UNIT: ["1개"] },
    284: { A_NAME: "korean-pear(intermediate-quality)", A_UNIT: ["1개"] },
    276: { A_NAME: "korean-pear(新高)", A_UNIT: ["1개"] },
    248: { A_NAME: "korean-pear(新高),big", A_UNIT: ["1개", "1 개"] },
    306: { A_NAME: "korean-pear(新高,600g)", A_UNIT: ["1개", "600g"] },
    28: { A_NAME: "apple", A_UNIT: ["1개"] },
    50: { A_NAME: "apple(富士)", A_UNIT: ["1개"] },
    305: { A_NAME: "apple(富士,300g)", A_UNIT: ["1개", "300g"] },
    270: { A_NAME: "apple(富士),middle", A_UNIT: ["1개"] },
    244: { A_NAME: "apple(富士),big", A_UNIT: ["1개", "1 개"] },
    279: { A_NAME: "apple(intermediate-quality)", A_UNIT: ["1개"] },
    277: { A_NAME: "kabocha", A_UNIT: ["1개"] },
    119: { A_NAME: "kabocha(incubator)", A_UNIT: ["1개"] },
    118: { A_NAME: "kabocha(incubator),intermediate-quality", A_UNIT: ["1개"] },
    312: { A_NAME: "zucchini", A_UNIT: ["1개", "1 개"] },
}
