// #region Global Imports
import Head from "next/head"
import styled from "styled-components"
// #endregion Global Imports

// #region Local Imports
import { Header, Button, Title, SizeCode } from "@Components"
import { useRouter } from "next/router"
import { ILayout } from "../Layout"
import { StyledWrap } from "./styled"

// #endregion Local Imports

export const Setting = function ({ children }: ILayout.IProps) {
    const router = useRouter()
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css" />
          </Head>
        <StyledWrap className="l_wrap">
                <Header centerTitle>
                <Button onClick={() => router.back()}>
                <i className="xi-angle-left" />
                        <span className="ir">뒤로가기</span>
              </Button>
                <Title as="h1">설정</Title>
              </Header>
                {children}
          </StyledWrap>
      </>
    )
}
