// #region Global Imports
import Head from "next/head"
import { useRouter } from "next/router"
// #endregion Global Imports

// #region Local Imports
import { Header, Button, Title } from "@Components"
import { ILayout } from "../Layout"
import { StyledWrap } from "./styled"
// #endregion Local Imports

export const Setting = function ({ children }: ILayout.IProps) {
    const router = useRouter()
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css"></link>
            </Head>
            <StyledWrap className="l_wrap">
                <Header title="설정">
                    <Button onClick={() => router.back()}>
                        <i className="xi-angle-left"></i>
                        <span className="ir">뒤로가기</span>
                    </Button>
                </Header>
                {children}
            </StyledWrap>
        </>
    )
}
